### ISSUE TITLE
Implement alternative page view with infinite scrolling for the story list

### ISSUE THREAD

**Issue by WilsonOh** [WilsonOh/hackernews-next#1]
## Background
Currently, hackernews-next uses a paginated model to display stories. This model works well but some users may want to have infinite scrolling instead. This would provide a smoother user experience and make the navigation of the site more intuitive.

## Tasks:
- [ ] Look into `useSWRInfinite` to implement infinite scrolling
- [ ] Use query/path params to separate the paginated view and infinite scrolling view
- [ ] Test the infinite scrolling using `playwright`

## Completion Criteria

- **Given** I'm on the infinite scrolling page view for the stories list
- **And** I scroll to the bottom of the page
- **Then** I should see a loading spinner at the bottom of the page, after which the next page of stories will be rendered. If there are no more stories, I should see an indicator/alert which tells me that there are no more stories.
